# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03122291dd6124620991e76321c24c9cb6bf88975d10b76094407fb2fa9f09c0dc84805d08551864e141f961d5b9394f5f8ad90219e82c31eecfbcb9ea02295b

test:
  secret_key_base: 19d2a7ae7998f3e7753198a62f72733a56d02e6fde6837d2e35027f3da663dcbee3f828f0731a2d42c65abe41f36e999258c6d37f1bb597313604ac6085940f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
